public  class MyIntroduction {
    public void printmyIntroduction() {

        string location = 'Brazil';
        string myhobby = ' Voleyball, Football and Swimming';
        boolean itBackground =false;
        string myprofession = ' Teacher ';
        string homecountry = ' Turkey ';

        system.debug('I live in'+ ' ' + location);
        system.debug('My hobbies are ' + ' ' + myhobby);
        system.debug('I am a ' + ' ' + myprofession);
        system.debug('I have IT background:' + ' ' + itBackground);
        system.debug('I am from' + ' ' + homecountry);

    

    }
}
